from test.TestBoundaryDaerahWisata import *
from test.TestBoundaryDestinasiWisata import *
from test.TestBoundaryListDestinasi import *
from test.TestBoundaryListTransportasi import *
from test.TestBoundaryRiwayat import *
from test.TestControllerBiayaTransportasi import *
from test.TestControllerCatatan import *
from test.TestControllerPerjalanan import *
from test.TestDaerahWisata import *
from test.TestDestinasiWisata import *
from test.TestListTransportasi import *
from test.TestMetodeTransportasi import *
from test.TestRiwayatPerjalanan import *