from classes.BoundaryDaerahWisata import *
from classes.BoundaryDestinasiWisata import *
from classes.BoundaryListDestinasi import *
from classes.BoundaryListTransportasi import *
from classes.BoundaryRiwayat import *
from classes.ControllerBiayaTransportasi import *
from classes.ControllerCatatan import *
from classes.ControllerPerjalanan import *
from classes.DaerahWisata import *
from classes.DestinasiWisata import *
from classes.ListTransportasi import *
from classes.MetodeTransportasi import *
from classes.RiwayatPerjalanan import *