from test import *
import unittest
test1 = TestBoundaryDaerahWisata()
test2 = TestBoundaryDestinasiWisata()
test3 = TestBoundaryListDestinasi()
test4 = TestBoundaryListTransportasi()
test5 = TestBoundaryRiwayat()
test6 = TestControllerBiayaTransportasi()
test7 = TestControllerCatatan()
test8 = TestControllerPerjalanan()
test9 = TestDaerahWisata()
test10 = TestDestinasiWisata()
test11 = TestListTransportasi()
test12 = TestMetodeTransportasi()
test13 = TestRiwayatPerjalanan()
unittest.main()